# Generated by Django 4.1.3 on 2022-11-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=50)),
                ("fullname", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="pics",
            name="id",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
